# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca90a52125ed326c8c636d4dc52ce32ed7bdd73d0a8f64177396cca4b9fa89f6c5ef43453b0618adeaaabddcad34a99a24c938fb2f29565e8ff1cd4b626d6ffd

test:
  secret_key_base: 4d3096c05cca8e17fe7310a11771bfa69162604ca0dc26f4d8ba938c97ce60fd1c4c07c1c28c483fa29b3d8bfd52a60917379a4ee05e8a800ed7cfc7eb1d07f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
